modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "morevillagers_mb"
version = "${version}"
displayName = "MoreVillagers:Missing Buildings"
authors = "ChoiceTheorem"
description = '''
Adds in missing buildings for morevillagers
'''
logoFile = "icon.png"

[[dependencies.morevillagers_mb]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.morevillagers_mb]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.morevillagers_mb]]
modId = "morevillagers"
type = "required"
versionRange = "[5.0.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "morevillagers_mb.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"